=== open-game-stack/open-game-stack-registry/schema/search-manifest/index.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "@context": {
      "type": "string",
      "minLength": 1
    },
    "@type": {
      "type": "string",
      "minLength": 1
    },
    "@id": {
      "type": "string",
      "format": "uri"
    },
    "name": {
      "type": "string",
      "minLength": 1
    },
    "about": {
      "minItems": 1,
      "maxItems": 1,
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "@id": {
            "type": "string",
            "format": "uri"
          },
          "@type": {
            "type": "string",
            "const": "ItemList"
          },
          "name": {
            "type": "string",
            "minLength": 1
          }
        },
        "required": [
          "@id",
          "@type"
        ],
        "additionalProperties": false
      }
    },
    "itemListElement": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "@type": {
            "type": "string",
            "const": "ListItem"
          },
          "item": {
            "type": "object",
            "properties": {
              "@id": {
                "type": "string",
                "format": "uri"
              },
              "@type": {
                "type": "string",
                "minLength": 1
              },
              "name": {
                "type": "string",
                "minLength": 1
              }
            },
            "required": [
              "@id",
              "@type"
            ],
            "additionalProperties": false
          }
        },
        "required": [
          "@type",
          "item"
        ],
        "additionalProperties": false
      }
    }
  },
  "required": [
    "@context",
    "@type",
    "@id",
    "name",
    "about",
    "itemListElement"
  ],
  "additionalProperties": false,
  "$id": "https://open-game-stack.github.io/open-game-stack-registry/schema/search-manifest"
}

=== open-game-stack/open-game-stack-registry/games/search/tags/index.json
{
  "$schema": "https://open-game-stack.github.io/open-game-stack-registry/schema/search-manifest",
  "@context": "https://schema.org/",
  "@type": "ItemList",
  "@id": "https://open-game-stack.github.io/open-game-stack-registry/games/search/tags",
  "name": "games search by tags",
  "about": [
    {
      "@id": "https://open-game-stack.github.io/open-game-stack-registry/games",
      "@type": "ItemList",
      "name": "games collection"
    }
  ],
  "itemListElement": []
}

=== open-game-stack/open-game-stack-registry/games/search/genre/index.json
{
  "$schema": "https://open-game-stack.github.io/open-game-stack-registry/schema/search-manifest",
  "@context": "https://schema.org/",
  "@type": "ItemList",
  "@id": "https://open-game-stack.github.io/open-game-stack-registry/games/search/genre",
  "name": "games search by genre",
  "about": [
    {
      "@id": "https://open-game-stack.github.io/open-game-stack-registry/games",
      "@type": "ItemList",
      "name": "games collection"
    }
  ],
  "itemListElement": [
    {
      "@type": "ListItem",
      "item": {
        "@id": "https://open-game-stack.github.io/open-game-stack-registry/games/search/genre/puzzle",
        "@type": "ItemList",
        "name": "puzzle"
      }
    },
    {
      "@type": "ListItem",
      "item": {
        "@id": "https://open-game-stack.github.io/open-game-stack-registry/games/search/genre/adventure",
        "@type": "ItemList",
        "name": "adventure"
      }
    }
  ]
}

=== open-game-stack/open-game-stack-registry/publishers/search/index.json
{
  "$schema": "https://kmturley.github.io/static-api-json-schema/schema/search-manifest",
  "@context": "https://schema.org/",
  "@type": "ItemList",
  "@id": "https://kmturley.github.io/static-api-json-schema/publishers/search",
  "name": "publishers search",
  "about": [
    {
      "@id": "https://kmturley.github.io/static-api-json-schema/publishers",
      "@type": "ItemList",
      "name": "publishers collection"
    }
  ],
  "itemListElement": [
    {
      "@type": "ListItem",
      "item": {
        "@id": "https://kmturley.github.io/static-api-json-schema/publishers/search/name",
        "@type": "ItemList",
        "name": "name"
      }
    }
  ]
}

=== open-game-stack/open-game-stack-registry/games/search/index.json
{
  "$schema": "https://kmturley.github.io/static-api-json-schema/schema/search-manifest",
  "@context": "https://schema.org/",
  "@type": "ItemList",
  "@id": "https://kmturley.github.io/static-api-json-schema/games/search",
  "name": "games search",
  "about": [
    {
      "@id": "https://kmturley.github.io/static-api-json-schema/games",
      "@type": "ItemList",
      "name": "games collection"
    }
  ],
  "itemListElement": [
    {
      "@type": "ListItem",
      "item": {
        "@id": "https://kmturley.github.io/static-api-json-schema/games/search/genre",
        "@type": "ItemList",
        "name": "genre"
      }
    },
    {
      "@type": "ListItem",
      "item": {
        "@id": "https://kmturley.github.io/static-api-json-schema/games/search/tags",
        "@type": "ItemList",
        "name": "tags"
      }
    },
    {
      "@type": "ListItem",
      "item": {
        "@id": "https://kmturley.github.io/static-api-json-schema/games/search/name",
        "@type": "ItemList",
        "name": "name"
      }
    }
  ]
}
